# Generated by Django 2.1.5 on 2019-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
